---
# SkyDNS service addon
- name: create SkyDNS pod file
  become: yes
  template:
    src: skydns-rc.yaml.j2
    dest: "{{ kubernetes_manifest_dir }}/skydns-rc.yaml"
  tags:
    - addons
    - skydns

- name: create SkyDNS service file
  become: yes
  template:
    src: skydns-svc.yaml.j2
    dest: "{{ kubernetes_manifest_dir }}/skydns-svc.yaml"
  tags:
    - addons
    - skydns

- name: Create SkyDNS replication controller
  become: yes
  kubernetes:
    api_endpoint: "{{ kubectl_endpoint }}"
    url_username: "{{ kubectl_username }}"
    url_password: "{{ kubectl_password }}"
    file_reference: "{{ kubernetes_manifest_dir }}/skydns-rc.yaml"
    state: present
  tags:
    - addons
    - skydns

- name: Create SkyDNS service
  become: yes
  kubernetes:
    api_endpoint: "{{ kubectl_endpoint }}"
    url_username: "{{ kubectl_username }}"
    url_password: "{{ kubectl_password }}"
    file_reference: "{{ kubernetes_manifest_dir }}/skydns-svc.yaml"
    state: present
  tags:
    - addons
    - skydns
