---
# defaults file for kube-master
kube_podmaster_version: 1.1
kube_etcd_servers: "{% for host in groups[etcd_servers_group] %}http://{{ hostvars[host].ansible_default_ipv4.address }}:4001{% if not loop.last %},{% endif %}{% endfor %}"
# Service account users
kube_users:
  kube:
    pass: changeme
    role: admin
  root:
    pass: changeme
    role: admin
